### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by timotheecour** [PMunch/protobuf-nim#3]
```
git clone https://github.com/PMunch/protobuf-nim
cd protobuf-nim
nim c -o:app -r protobuf.nim
protobuf.nim(123, 10) Error: cannot open '../combparser/combparser'

cd ..
git clone https://github.com/PMunch/combparser
cd -
nim c -o:app -r protobuf.nim
protobuf.nim(180, 17) Error: undeclared identifier: 'charmatch'
```

having a nimble package would simplify things (cf https://github.com/PMunch/protobuf-nim/issues/2)

**Comment by PMunch** [comment]
Ah yes, as I was developing combparser at the same time as this I kept it in a folder next to protobuf. And since neither have a nimble package yet I kept it that way. If you clone the combparser repo in the same folder as the cloned protobuf repo it should work. Note however that I'm still in a refactoring phase of the error messages so you would need to checkout the `errors3` branch of combparser for it to work. This will be fixed shortly and both combparser and protobuf will be available through Nimble.
