### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by timotheecour** [PMunch/protobuf-nim#6]
- [x] the readme doesn't render well your code sections in https://github.com/PMunch/protobuf-nim
eg: https://www.dropbox.com/s/0j51wbl2i5wojnm/Screenshot%202018-03-29%2017.40.01.png?dl=0

- [x] ~~instead of indenting to define code blocks IIRC it's more standard to use triple quotes, with benefits of not having to indent every line (easier to copy paste) and allowing to specify syntax (eg nim or proto) for syntax highlighting eg:~~

```nim
type
  our_package_ExampleMessage = object
    simpleField: int32
```

instead of:

  type
    our_package_ExampleMessage = object
      simpleField: int32

- [x] would be really nice to have a section on _how to use_ , eg analog to https://raw.githubusercontent.com/oswjk/protobuf-nim/master/README.md 

>And you can use it like this:
```nim
let message = newTest1()
setA(message, 150)
let pbso = newProtobufStream(newFileStream(stdout))
writeTest1(pbso, message)
```

- [x] maybe also reply on this thread: https://forum.nim-lang.org/t/3687 Protocol Buffer library for Nim

**Comment by PMunch** [comment]
Triple backticks are used to mark code blocks in markdown, but this is ReStructured Text. Since Nim uses RST for it's documentation I wrote it once in RST and then wrote a simple script that extracts the RST from the module definition and puts it into a README file. I'll look into specifying syntax though for proper highlihting, and I'll make sure it renders well both in the documentation and the GitHub page. To generate the full documentation run `nim doc protobuf.nim`.

I'll add a short howto snippet as well.

Hmm, I'm not sure if I even have a Nim forum account. But I guess this is a good a time as any to create one 😃

**Comment by PMunch** [comment]
Fixed the formatting now, and added an example. Let me know if it's not clear enough, I tried to keep it brief but informative.

**Comment by timotheecour** [comment]
> Hmm, I'm not sure if I even have a Nim forum account. But I guess this is a good a time as any to create one 😃

just replied there: https://forum.nim-lang.org/t/3687/1#23112

**Comment by PMunch** [comment]
Yeah I commented as well, but I guess my brand new account might be under moderation if you didn't see it? Does the documentation look good by the way, should I close this issue?

**Comment by timotheecour** [comment]
not seeing your reply, maybe under moderation indeed... shd be fast (if still doesn't work, maybe ask on gitter or irc?)
ya, thanks, closing!
