### ISSUE TITLE
setters (and getters?) should work without calling `init` on Nullable fields, as in C++

### ISSUE THREAD

**Issue by timotheecour** [PMunch/protobuf-nim#7]
- [x] setter
this is pretty much the same as https://github.com/msoucy/dproto/issues/117 

```nim
msg.nested = ExampleMessage_SubMessage(aField: 100)
# we should allow the simpler:
msg.nested.aField: 100
```
basically, would call create the SubMessage upon 1st access.

- [x] getter

the question here is what's the desired behavior for getting a submessage that wasn't constructed
this is one possibility:
```
var msg: ExampleMessage
assert msg.nested.aField == 0 # default value
```
another is to throw.
CHECKME: check behavior of C++ in this case

**Comment by PMunch** [comment]
This already works as expected. Since all of these are added as objects and not `ref object` all object fields are initialised to their Nim default value. Your setter example works if you just change the colon to an equality symbol. And the getter example would pass as 0 is indeed the default value for integer fields.

**Comment by timotheecour** [comment]
indeed, thanks; however, see https://github.com/PMunch/protobuf-nim/issues/8
